export const QUERIES_KEYS = {
  GET_POLICIES: "GET_POLICIES",
  GET_NEWS: "GET_NEWS",
  GET_USER: "GET_USER",
  GET_TATOOCARE: "GET_TATOOCARE",
  GET_FAQ: "GET_FAQ",
  GET_BOOKING: "GET_BOOKING",
  GET_ARTIST: "GET_ARTIST",
};
